[package]
name = "meowtsun/mug"
description = "My collection of generic runtime utilities"
version = "1.0.0"
authors = ["Meowtsun"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
